language: node_js
node_js:
  - "8"
install:
  - npm install -g pm2 nsp
deploy:
  provider: script
  script:
    - pm2 deploy deploy/ecosystem.config.js setup
    - pm2 deploy deploy/ecosystem.config.js production
  on:
    branch: master
notifications:
    slack: heftybyte:MfzjodikjxZSS1Vbqyg8inIv
